-- Supabase Schema for Pre-Sales Agent

-- Agents Table
CREATE TABLE IF NOT EXISTS public.agents (
    email TEXT PRIMARY KEY,
    name TEXT,
    password TEXT,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Clients Table
CREATE TABLE IF NOT EXISTS public.clients (
    client_id TEXT PRIMARY KEY,
    company TEXT NOT NULL,
    industry TEXT,
    email TEXT,
    notes TEXT,
    size TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tracking Table
CREATE TABLE IF NOT EXISTS public.tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id TEXT REFERENCES public.clients(client_id) ON DELETE CASCADE,
    event TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    timestamp TIMESTAMPTZ DEFAULT now()
);

-- Proposals Table
CREATE TABLE IF NOT EXISTS public.proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id TEXT REFERENCES public.clients(client_id) ON DELETE CASCADE,
    version INT NOT NULL,
    title TEXT,
    proposal_html TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(client_id, version)
);

-- Enable RLS (Optional, but recommended for production)
-- For now, we assume service_role or anon key with permissve policies for rapid setup
ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposals ENABLE ROW LEVEL SECURITY;

-- Creating permissive policies for development
CREATE POLICY "Allow all" ON public.agents FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON public.clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON public.tracking FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON public.proposals FOR ALL USING (true) WITH CHECK (true);
